# Generated by Django 4.2.6 on 2024-01-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_user_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
    ]
